baseURL: "https://devamshi.github.io/v8r/"
languageCode: en-us
title: "127.0.0.1"
theme: "PaperMod"
paginate: 5

minify:
  disableXML: true

menu:
  main:
    - identifier: archives 
      name: Archives 
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30
    - identifier: about 
      name: About Me
      url: /about/
      weight: 40
params:

  env: production

  disableThemeToggle: false

  homeInfoParams:
    Title: "Hey, I'm vamshidhar."
    Content: > 
      Welcome to my blog. Here, I share my learnings on tech, life and health.
      

  socialIcons: 
    - name: github
      title: Github profile
      url: "https://github.com/deVamshi"
    - name: linkedin
      title: LinkedIn profile
      url: "https://www.linkedin.com/in/vamshidhar-telugu-b10259181/"
    - name: buymeacoffee
      title: Support my work
      url: "https://buymeacoffee.com/devamshi"

outputs:
  home:
    - HTML
    - RSS
    - JSON # necessary for search

